# .goreleaser.yaml
version: 1

before:
  hooks:
    - go mod tidy

builds:
  - id: p1nrgy
    main: .
    binary: p1nrgy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    builds:
      - p1nrgy
    format: tar.gz
    # Rename darwin to macOS using a template instead of the (removed) `replacements` field
    name_template: >-
      {{ .Binary }}_{{ .Version }}_{{- if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

# signs:
#   - artifacts: checksum
#     cmd: cosign
#     args:
#       - sign-blob
#       - --key=cosign.key
#       - --output
#       - "${artifact}.sig"
#       - "${artifact}"

dockers:
  - image_templates:
      - "ghcr.io/hans-2022/p1nrgy:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    extra_files:
      - entrypoint.sh
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "ghcr.io/hans-2022/p1nrgy:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    extra_files:
      - entrypoint.sh
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  - name_template: ghcr.io/hans-2022/p1nrgy:{{ .Version }}
    image_templates:
      - ghcr.io/hans-2022/p1nrgy:{{ .Version }}-amd64
      - ghcr.io/hans-2022/p1nrgy:{{ .Version }}-arm64
  - name_template: ghcr.io/hans-2022/p1nrgy:latest
    image_templates:
      - ghcr.io/hans-2022/p1nrgy:{{ .Version }}-amd64
      - ghcr.io/hans-2022/p1nrgy:{{ .Version }}-arm64
      
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: "hans-2022"
    name: "p1ngry"
  draft: false
  prerelease: auto
